/**
 * 像素画 - 笔刷渲染和管理
 */

PixelPaintSkill._renderBrushes = function() {
    var self = this; var el = this._q('#ppBrushGrid'); el.innerHTML = '';
    this._brushes.forEach(function(brush, i) { var div = document.createElement('div'); div.className = 'pp-brush-item' + (i === self._selectedBrushIdx ? ' selected' : ''); div.title = brush.name; var rows = brush.data.length, cols = brush.data[0].length, s = Math.min(Math.floor(34 / Math.max(rows, cols)), 8); var c = document.createElement('canvas'); c.width = cols * s; c.height = rows * s; var bctx = c.getContext('2d'); brush.data.forEach(function(row, r) { row.forEach(function(color, col) { if (color) { if (typeof color === 'number') color = self._getColor(color); if (!color) return; bctx.fillStyle = color.startsWith('#') ? color : '#' + color; bctx.fillRect(col * s, r * s, s, s); } }); }); div.appendChild(c); var label = document.createElement('span'); label.className = 'pp-brush-item-label'; label.textContent = brush.name; div.appendChild(label); div.onclick = function() { if (self._deleteBrushMode) { self._brushes.splice(i, 1); if (!self._brushes.length) self._nextBrushId = 1; if (self._selectedBrushIdx === i) self._selectedBrushIdx = -1; else if (self._selectedBrushIdx > i) self._selectedBrushIdx--; self._renderBrushes(); self._autoSave(); } else { self._selectedBrushIdx = (self._selectedBrushIdx === i) ? -1 : i; if (self._selectedBrushIdx >= 0) self._setTool('stamp'); self._renderBrushes(); } }; el.appendChild(div); });
    var sec = this._q('#ppSecBrushes');
    if (sec && el) { var header = sec.querySelector('.pp-section-header'); var hh = header ? header.offsetHeight : 0; el.style.maxHeight = Math.max(0, sec.clientHeight - hh) + 'px'; el.style.overflowY = 'auto'; }
};

PixelPaintSkill._setTool = function(tool) { this._currentTool = tool; this._qa('.pp-tool-btn[data-tool]').forEach(function(btn) { btn.classList.toggle('active', btn.dataset.tool === tool); }); if (tool !== 'select') { this._selection = null; this._selData = null; this._selLocked = false; this._selDragging = false; this._drawSelection(); } };

PixelPaintSkill._floodFill = function(data, sx, sy, newId, w, h) { var target = data[sy][sx]; if (target === newId) return; var stack = [[sx, sy]], visited = new Set(); while (stack.length) { var p = stack.pop(), x = p[0], y = p[1], k = y * w + x; if (visited.has(k) || x < 0 || x >= w || y < 0 || y >= h || data[y][x] !== target) continue; visited.add(k); data[y][x] = newId; stack.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]); } };

PixelPaintSkill._stampBrush = function(data, brush, gx, gy, w, h) { var self = this, colorMap = new Map(); this._pixelBlocks.forEach(function(bl) { colorMap.set(bl.color.toLowerCase(), bl.id); }); var needRenderGrid = false; for (var r = 0; r < brush.data.length; r++) for (var c = 0; c < brush.data[r].length; c++) { var color = brush.data[r][c]; if (!color) continue; var px = gx + c, py = gy + r; if (px < 0 || px >= w || py < 0 || py >= h) continue; var hex = (color.startsWith('#') ? color : '#' + color).toLowerCase(); var id = colorMap.get(hex); if (id == null) { id = self._nextBlockId++; self._pixelBlocks.push({id:id,color:hex,name:TEXTS.COLOR_PREFIX + id}); colorMap.set(hex,id); needRenderGrid = true; } data[py][px] = id; if (self._mergedData) self._mergedData[py][px] = id; } if (needRenderGrid) this._renderPixelGrid(); };

PixelPaintSkill._saveBrush = function() { if (!this._selData || !this._selData.length) { this._showModal(TEXTS.MSG_SELECT_AREA_FIRST, [{text:TEXTS.BTN_OK,value:true,primary:true}]); return; } var hasContent = this._selData.some(function(row) { return row.some(function(c) { return c !== null && c !== 0; }); }); if (!hasContent) { this._showModal(TEXTS.MSG_NO_CONTENT_IN_SEL, [{text:TEXTS.BTN_OK,value:true,primary:true}]); return; } var data = this._selData.map(function(row) { return row.slice(); }); this._nextBrushId++; this._brushes.push({id:this._nextBrushId,name:String(this._brushes.length+1),data:data,w:data[0].length,h:data.length}); this._selectedBrushIdx = this._brushes.length - 1; this._renderBrushes(); this._autoSave(); this._updateInfo(); };

PixelPaintSkill._doClearBrush = function() { var self = this; (async function() { var ok = await self._showModal(TEXTS.MSG_CONFIRM_CLEAR_BRUSHES, [{text:TEXTS.BTN_CANCEL,value:false},{text:TEXTS.BTN_CONFIRM_CLEAR,value:true,primary:true}]); if (!ok) return; self._brushes.length = 0; self._nextBrushId = 1; self._selectedBrushIdx = -1; self._renderBrushes(); self._autoSave(); })(); };

PixelPaintSkill._doExportBrush = function() { if (!this._brushes.length) { this._showModal(TEXTS.MSG_NO_BRUSHES_TO_EXPORT, [{text:TEXTS.BTN_OK,value:true,primary:true}]); return; } var json = JSON.stringify({brushes:this._brushes,nextBrushId:this._nextBrushId}); var blob = new Blob([json],{type:'application/json'}); var link = document.createElement('a'); link.download = TEXTS.FILENAME_BRUSHES; link.href = URL.createObjectURL(blob); link.click(); URL.revokeObjectURL(link.href); };

PixelPaintSkill._handleImportBrush = function(e) { var self = this, file = e.target.files[0]; if (!file) return; var reader = new FileReader(); reader.onload = function() { try { var json = JSON.parse(reader.result); if (json.brushes && Array.isArray(json.brushes)) { json.brushes.forEach(function(b) { if (!b.data) return; self._nextBrushId++; self._brushes.push({id:self._nextBrushId,name:String(self._brushes.length+1),data:b.data,w:b.w,h:b.h}); }); self._renderBrushes(); self._autoSave(); self._showModal(TEXTS.MSG_BRUSHES_IMPORTED + json.brushes.filter(function(b){return b.data;}).length + TEXTS.MSG_BRUSHES_IMPORTED_SUFFIX, [{text:TEXTS.BTN_GOT_IT,value:true,primary:true}]); } } catch(err) { self._showModal(TEXTS.MSG_IMPORT_FAILED, [{text:TEXTS.BTN_OK,value:true,primary:true}]); } }; reader.readAsText(file); e.target.value = ''; };
