/**
 * 像素画 - 色块渲染和管理
 */

PixelPaintSkill._renderPixelGrid = function() {
    var self = this; var el = this._q('#ppPixelGrid'); el.innerHTML = '';
    this._pixelBlocks.forEach(function(b) { var div = document.createElement('div'); div.className = 'pp-pixel-cell' + (b.id === self._selectedBlock ? ' selected' : '') + (self._mergeColorMode && self._mergeColorIds.indexOf(b.id) !== -1 ? ' merge-selected' : ''); div.innerHTML = '<div class="pp-pixel-cell-color" style="background:' + b.color + '"></div><span class="pp-pixel-cell-num">' + b.id + '</span>'; div.onclick = function() { self._onPixelCellClick(b); }; el.appendChild(div); });
};

PixelPaintSkill._onPixelCellClick = function(b) {
    var self = this;
    if (this._mergeColorMode) { var idx = this._mergeColorIds.indexOf(b.id); if (idx === -1) this._mergeColorIds.push(b.id); else this._mergeColorIds.splice(idx, 1); this._renderPixelGrid(); }
    else if (this._deleteColorMode) { (async function() { var tab = self._getActiveTab(), usedInCanvas = false; if (tab) { for (var y = 0; y < tab.h && !usedInCanvas; y++) for (var x = 0; x < tab.w; x++) { if (tab.data[y][x] === b.id) { usedInCanvas = true; break; } } } if (usedInCanvas) { var ok = await self._showModal(TEXTS.MSG_COLOR_IN_USE_PRE + b.id + TEXTS.MSG_COLOR_IN_USE_POST, [{text:TEXTS.BTN_CANCEL,value:false},{text:TEXTS.BTN_CONFIRM_DELETE,value:true,primary:true}]); if (!ok) return; if (tab) { self._pushUndo(tab); for (var y2 = 0; y2 < tab.h; y2++) for (var x2 = 0; x2 < tab.w; x2++) { if (tab.data[y2][x2] === b.id) tab.data[y2][x2] = 0; } self._mergedData = null; self._saveCurrentFrame(); self._drawCanvas(); self._renderTimeline(); } } var idx2 = self._pixelBlocks.indexOf(b); if (idx2 !== -1) { self._pixelBlocks.splice(idx2, 1); if (!self._pixelBlocks.length) self._nextBlockId = 1; self._thumbCache.clear(); self._mergedData = null; self._renderPixelGrid(); self._drawCanvas(); self._autoSave(); } })(); }
    else { this._selectedBlock = b.id; this._renderPixelGrid(); }
};

PixelPaintSkill._handleAddColor = function(hex) { if (this._editColorMode) { var b = this._pixelBlocks.find(function(bl) { return bl.id === this._selectedBlock; }.bind(this)); if (b) { b.color = hex; this._thumbCache.clear(); this._renderPixelGrid(); this._drawCanvas(); this._autoSave(); } } else { var exists = this._pixelBlocks.find(function(b2) { return b2.color.toLowerCase() === hex.toLowerCase(); }); if (!exists) { var newId = this._nextBlockId; this._pixelBlocks.push({id:newId,color:hex,name:TEXTS.COLOR_PREFIX + newId}); this._nextBlockId++; this._selectedBlock = newId; this._renderPixelGrid(); this._autoSave(); } } this._editColorMode = false; };

PixelPaintSkill._handleEditColor = function() { var self = this; (async function() { var b = self._pixelBlocks.find(function(bl) { return bl.id === self._selectedBlock; }); if (!b) { await self._showModal(TEXTS.MSG_SELECT_COLOR_FIRST, [{text:TEXTS.BTN_OK,value:true,primary:true}]); return; } self._editColorMode = true; var input = self._q('#ppAddColorInput'); input.value = b.color; input.click(); })(); };

PixelPaintSkill._doClearColor = function() { var self = this; (async function() { var ok = await self._showModal(TEXTS.MSG_CONFIRM_CLEAR_COLORS, [{text:TEXTS.BTN_CANCEL,value:false},{text:TEXTS.BTN_CONFIRM_CLEAR,value:true,primary:true}]); if (!ok) return; self._pixelBlocks.length = 0; self._nextBlockId = 1; self._selectedBlock = 1; var tab = self._getActiveTab(); if (tab) { self._pushUndo(tab); for (var y = 0; y < tab.h; y++) for (var x = 0; x < tab.w; x++) tab.data[y][x] = 0; self._mergedData = null; self._saveCurrentFrame(); self._drawCanvas(); self._renderTimeline(); } self._renderPixelGrid(); self._autoSave(); })(); };

PixelPaintSkill._handleMergeColor = function() { var self = this; (async function() { var btn = self._q('#ppMergeColorBtn'); if (!self._mergeColorMode) { self._mergeColorMode = true; self._mergeColorIds = []; btn.classList.add('active'); self._renderPixelGrid(); } else { if (self._mergeColorIds.length < 2) { self._mergeColorMode = false; self._mergeColorIds = []; btn.classList.remove('active'); self._renderPixelGrid(); return; } var targetId = self._mergeColorIds[0], removeIds = self._mergeColorIds.slice(1); var ok = await self._showModal(TEXTS.MSG_MERGE_PRE + removeIds.length + TEXTS.MSG_MERGE_MID + targetId + TEXTS.MSG_MERGE_POST, [{text:TEXTS.BTN_CANCEL,value:false},{text:TEXTS.BTN_CONFIRM_MERGE,value:true,primary:true}]); if (!ok) { self._mergeColorMode = false; self._mergeColorIds = []; btn.classList.remove('active'); self._renderPixelGrid(); return; } var tab = self._getActiveTab(); if (tab) { self._pushUndo(tab); for (var y = 0; y < tab.h; y++) for (var x = 0; x < tab.w; x++) { if (removeIds.indexOf(tab.data[y][x]) !== -1) tab.data[y][x] = targetId; } self._mergedData = null; self._saveCurrentFrame(); self._drawCanvas(); self._renderTimeline(); } for (var li = 0; li < self._layers.length; li++) { if (!self._frameData[li]) continue; for (var f = 0; f < self._frameCount; f++) { if (!self._frameData[li][f]) continue; var fd = self._frameData[li][f]; for (var fy = 0; fy < fd.length; fy++) for (var fx = 0; fx < fd[0].length; fx++) { if (removeIds.indexOf(fd[fy][fx]) !== -1) fd[fy][fx] = targetId; } } } removeIds.forEach(function(rid) { var idx = self._pixelBlocks.findIndex(function(b) { return b.id === rid; }); if (idx !== -1) self._pixelBlocks.splice(idx, 1); }); self._mergeColorMode = false; self._mergeColorIds = []; btn.classList.remove('active'); self._renderPixelGrid(); self._autoSave(); } })(); };
