/**
 * ============================================
 *   像素画 - 文本常量
 * ============================================
 */

var TEXTS = {
    // Long tooltip texts for secondary buttons
    TIP_ADD_COLOR: '添加色块：点击后弹出取色器，选择颜色后添加为新色块',
    TIP_EDIT_COLOR: '编辑色块：修改当前选中色块的颜色，画布上使用该色块的像素会自动更新',
    TIP_DEL_COLOR: '删除色块：点击后进入删除模式，再点击色块即可删除，画布上对应像素也会被清除',
    TIP_CLEAR_COLOR: '清空色块：删除所有色块，画布上使用这些色块的像素也会被清除',
    TIP_MERGE_COLOR: '合并色块：1.点击此按钮激活合并模式\n2.点第一个色块作为保留色\n3.点其他要合并的色块\n4.再次点击此按钮完成合并，被选中的色块像素全部替换为保留色',
    TIP_ADD_BRUSH: '新建笔刷：创建一个空白笔刷，可在笔刷网格上手动绘制',
    TIP_DEL_BRUSH: '删除笔刷：删除当前选中的笔刷',
    TIP_CLEAR_BRUSH: '清空笔刷：删除所有已保存的笔刷',
    TIP_EXPORT_BRUSH: '导出笔刷：将所有笔刷导出为JSON文件，可用于备份',
    TIP_IMPORT_BRUSH: '导入笔刷：从JSON文件导入笔刷，会追加到现有笔刷列表',
    TIP_PICKER_SHORT: '取色器：选择颜色后点击+按钮添加为新色块',
    TIP_RESET_LONG: '重置：清除所有数据，恢复到初始状态（画布/色块/笔刷全部清空）',
    TIP_CLEAR_LONG: '清空：清除当前画布所有像素，恢复为空白',
    TIP_IMPORT_DATA_LONG: '入数据：导入之前导出的JSON数据文件，恢复画布内容',
    TIP_IMPORT_IMG_LONG: '入图片：导入外部图片，自动减色为色块数量并映射到画布',
    TIP_EXPORT_DATA_LONG: '存数据：将当前画布数据导出为JSON文件，可用于备份和迁移',
    TIP_EXPORT_FULL_LONG: '存全图：导出完整画布为PNG图片，透明区域保留透明',
    TIP_EXPORT_TRIM_LONG: '存裁图：导出画布为PNG图片，自动裁剪掉四周空白区域',
    TIP_SAVE_BRUSH_LONG: '存刷：先用选区工具框选一块区域\n再点此按钮保存为笔刷',
    TIP_SELECT_LONG: '选区：在画布上拖拽框选矩形区域\n选中后可移动/翻转/旋转',
    TIP_STAMP_LONG: '盖章：选中一个笔刷后\n左键在画布上点击放置笔刷图案',
    TIP_FLIP_H_LONG: '左右翻转：将选区内容水平镜像翻转',
    TIP_FLIP_V_LONG: '上下翻转：将选区内容垂直镜像翻转',
    TIP_ROTATE_LONG: '旋转：将选区内容顺时针旋转90度',
    TIP_UNDO_LONG: '撤销：回退上一步操作，支持多步撤销',
    TIP_REDO_LONG: '重做：恢复被撤销的操作',

    NAME: '像素画v2',
    DESC: '数字像素绘画系统，支持多标签页、动画表、图层、笔刷',
    CLOSE: '关',
    CANVAS_SIZE: '画布尺寸',
    NUM_DISPLAY: '数字显示',
    GRID_DISPLAY: '网格显示',
    TOOLS: '工具',
    COLORS: '色块',
    BRUSHES: '笔刷',
    SIZE_8: '8x8', SIZE_16: '16x16', SIZE_32: '32x32', SIZE_64: '64x64',
    APPLY: '应用',
    TOOL_BRUSH: '画笔', TOOL_ERASER: '橡皮', TOOL_FILL: '填充',
    TOOL_PICKER: '找色', TOOL_SELECT: '选区', TOOL_STAMP: '盖章',
    TIP_BRUSH: '画笔：左键在画布上绘制当前选中的色块像素',
    TIP_ERASER: '橡皮：左键擦除像素，将像素变为透明(0)',
    TIP_FILL: '填充：点击一个像素，将该像素所在的连通区域全部填充为当前色块',
    TIP_PICKER: '找色：点击画布上的像素，自动选中该像素对应的色块',
    TIP_SELECT: '选区：框选后拖拽移动，点击[左右/上下/旋转]可变形',
    TIP_STAMP: '盖章：用当前笔刷在画布上盖章绘制，自动补色块',
    UNDO: '撤销', REDO: '重做', SAVE_BRUSH: '存刷',
    EXPORT_DATA: '存数据', EXPORT_FULL: '存全图', EXPORT_TRIM: '存裁图',
    IMPORT_DATA: '入数据', IMPORT_IMG: '入图片',
    CLEAR: '清空', RESET: '重置',
    FLIP_H: '左右', FLIP_V: '上下', ROTATE: '旋转',
    PLAY: '播放', PAUSE: '暂停',
    DEL_FRAME: '删帧', DEL_LAYER: '删层',
    EXPORT_SPRITE: '导出帧序列', EXPORT_LAYER_SPRITE: '导出层序列',
    TIP_UNDO: '撤销：撤销上一步操作',
    TIP_REDO: '重做：恢复已撤销的操作',
    TIP_SAVE_BRUSH: '存刷：将当前选区保存为笔刷',
    TIP_EXPORT_FULL: '存全图：下载为 PNG 文件（含背景网格）',
    TIP_EXPORT_TRIM: '存裁图：裁剪空白边缘后下载 PNG',
    TIP_EXPORT_DATA: '存数据：导出完整的帧/层/色块数据为 JSON，可用于恢复编辑',
    TIP_IMPORT_DATA: '入数据：从 JSON 文件恢复项目（可包含帧动画）',
    TIP_IMPORT_IMG: '入图片：将外部 PNG/JPEG 导入为像素画',
    TIP_CLEAR: '清空：清空当前画布内容',
    TIP_RESET: '重置：恢复初始默认设置',
    TIP_FLIP_H: '左右：水平翻转选区',
    TIP_FLIP_V: '上下：垂直翻转选区',
    TIP_ROTATE: '旋转：顺时针旋转 90°',
    TIP_PLAY: '播放：播放动画预览，点击暂停',
    TIP_DEL_FRAME: '删帧：删除当前帧',
    TIP_DEL_LAYER: '删层：删除当前图层',
    TIP_EXPORT_SPRITE: '导出帧序列：将各帧合并为长条雪碧图 PNG',
    TIP_EXPORT_LAYER_SPRITE: '导出层序列：将各层各帧展开为矩阵 PNG',
    CALIBRATE: '像素对齐',
    TARGET_GRID: '目标网格',
    PALETTE_LABEL: '调色盘',
    PAL_PICO8: 'Pico-8 标准16色',
    PAL_GAMEBOY: 'GameBoy 4色绿',
    PAL_NES: 'NES 32色',
    PAL_CUSTOM16: '自适应16色',
    NO_DITHER: '无交错',
    DOT_DITHER: '点交错',
    BAYER_2X2: 'Bayer 2x2 (粗颗粒)',
    BAYER_4X4: 'Bayer 4x4 (标准)',
    EXEC_CALIBRATE: '执行校准',
    COL_HEADER: '#',
    ADD_FRAME: '添加帧',
    EYE_VISIBLE: 'V',
    ADD_LAYER: '添加图层',
    LAYER_PREFIX: '图层',
    COLOR_RED: '红', COLOR_ORANGE: '橙', COLOR_YELLOW: '黄',
    COLOR_GREEN: '绿', COLOR_BLUE: '蓝', COLOR_PURPLE: '紫',
    COLOR_CYAN: '青', COLOR_WHITE: '白', COLOR_GRAY: '灰', COLOR_DARK_BLUE: '深蓝',
    STATUS_SIZE_SEP: ' x ',
    STATUS_ZOOM_PREFIX: ' | 缩放 ',
    STATUS_ZOOM_SUFFIX: '% | 右键拖拽 . 滚轮缩放',
    ZOOM: '缩放',     COMMON: '公共',
    FPS: '帧率',
    MSG_SELECT_AREA_FOR_BRUSH: '请用选区工具框选区域，然后点击"存刷"',
    MSG_SELECT_AREA_FIRST: '请先用选区工具框选一个区域',
    MSG_NO_CONTENT_IN_SEL: '框选区域内没有像素内容',
    MSG_SELECT_COLOR_FIRST: '请先选中一个色块',
    MSG_CONFIRM_CLEAR_COLORS: '确定清空所有色块？画布中使用该色块的像素将变为空。',
    MSG_CONFIRM_CLEAR_BRUSHES: '确定清空所有笔刷？',
    MSG_NO_BRUSHES_TO_EXPORT: '没有笔刷可导出',
    MSG_BRUSHES_IMPORTED: '已导入',
    MSG_BRUSHES_IMPORTED_SUFFIX: '个笔刷',
    MSG_IMPORT_FAILED: '导入失败：文件格式错误',
    MSG_CONFIRM_CLEAR_CANVAS: '确定要清空当前画布吗？\n此操作可通过撤销恢复。',
    MSG_CONFIRM_RESET: '确定要恢复初始设置吗？\n将清除所有画布、色块、笔刷、图层、帧数据。',
    MSG_COLOR_MISSING: '当前色块已不存在，请重新选择一个色块',
    MSG_AT_LEAST_ONE_FRAME: '至少保留一帧',
    MSG_AT_LEAST_ONE_LAYER: '至少保留一个图层',
    MSG_COLOR_IN_USE_PRE: '色块 #',
    MSG_COLOR_IN_USE_POST: ' 正在画布中使用，确定删除？\n删除后画布中该色块像素将变为空(0)',
    MSG_MERGE_PRE: '将 ',
    MSG_MERGE_MID: ' 个色块合并到色块#',
    MSG_MERGE_POST: '？',
    MSG_DEL_FRAME_PRE: '确定删除第 ',
    MSG_DEL_FRAME_POST: ' 帧吗？',
    MSG_DEL_LAYER_PRE: '确定删除第 ',
    MSG_DEL_LAYER_POST: ' 层吗？',
    BTN_OK: '知道了', BTN_CONFIRM: '确定',
    BTN_GOT_IT: '好的',
    BTN_CANCEL: '取消',
    BTN_CONFIRM_DELETE: '确定删除', BTN_CONFIRM_CLEAR: '确定清空',
    BTN_CONFIRM_RESET: '确定重置', BTN_CONFIRM_MERGE: '确定合并',
    FILENAME_DATA: '_data.json', FILENAME_PNG: '.png',
    FILENAME_TRIM: '_trim.png', FILENAME_SPRITE: '_sprite.png',
    FILENAME_LAYER_SEQ: '_layer_seq.png', FILENAME_BRUSHES: 'brushes.json',
    CLOUD_IMPORT: '盘导入',
    CLOUD_IMPORT_TITLE: '从本地云盘导入图片',
    CLOUD_EXPORT: '盘导出',
    CLOUD_EXPORT_TITLE: '导出当前画布并存入本地云盘',
    SAVED_TO_CLOUD: '已存入云盘',
    PROCESSING_IMAGE: '正在处理图片...',
    CLOUD_IMG_FAILED: '云盘图片加载失败',
    CLOUD_TAG: '像素画',
    COLOR_PREFIX: '色',
};
