/**
 * 像素画 - 画布交互（鼠标/键盘/滚轮）
 */

PixelPaintSkill._onCanvasMouseDown = function(e) {
    var self = this;
    if (e.button === 2) { this._isPanning = true; this._panStartX = e.clientX; this._panStartY = e.clientY; this._canvasArea.style.cursor = 'grabbing'; return; }
    if (e.button !== 0) return;
    var pos = this._screenToGrid(e); if (!pos) return; var tab = this._getActiveTab();
    if (this._currentTool !== 'picker') this._cfLock = true;
    if (this._currentTool === 'brush') { (async function() { if (!await self._ensureValidBlock()) return; self._pushUndo(tab); self._isDrawing = true; self._lastDrawPos = {x:pos.x,y:pos.y}; tab.data[pos.y][pos.x] = self._selectedBlock; if (self._mergedData) self._mergedData[pos.y][pos.x] = self._selectedBlock; self._drawCanvas(); })(); }
    else if (this._currentTool === 'eraser') { this._pushUndo(tab); this._isDrawing = true; this._lastDrawPos = {x:pos.x,y:pos.y}; tab.data[pos.y][pos.x] = 0; if (this._mergedData) this._mergedData[pos.y][pos.x] = 0; this._drawCanvas(); }
    else if (this._currentTool === 'fill') { (async function() { if (!await self._ensureValidBlock()) return; self._pushUndo(tab); self._floodFill(tab.data, pos.x, pos.y, self._selectedBlock, tab.w, tab.h); self._mergedData = null; self._saveCurrentFrame(); self._drawCanvas(); self._renderTimeline(); self._autoSave(); })(); }
    else if (this._currentTool === 'picker') { var id = tab.data[pos.y][pos.x]; if (id !== 0) { this._selectedBlock = id; this._renderPixelGrid(); this._autoSave(); } }
    else if (this._currentTool === 'select') { if (this._selLocked && this._selData) { var sh = this._selData.length, sw = this._selData[0].length; if (pos.x >= this._selX && pos.x < this._selX + sw && pos.y >= this._selY && pos.y < this._selY + sh) { this._pushUndo(tab); for (var y = this._selY; y < this._selY + sh; y++) for (var x = this._selX; x < this._selX + sw; x++) { tab.data[y][x] = 0; if (this._mergedData) this._mergedData[y][x] = 0; } this._drawCanvas(); this._selDragging = true; this._selDragOffX = pos.x - this._selX; this._selDragOffY = pos.y - this._selY; this._isDrawing = true; } else { this._cancelSelection(); this._isDrawing = true; this._drawStart = pos; this._selection = {x1:pos.x,y1:pos.y,x2:pos.x,y2:pos.y}; this._drawSelection(); } } else { this._isDrawing = true; this._drawStart = pos; this._selection = {x1:pos.x,y1:pos.y,x2:pos.x,y2:pos.y}; this._drawSelection(); } }
    else if (this._currentTool === 'stamp') { if (this._selectedBrushIdx >= 0 && this._brushes[this._selectedBrushIdx]) { this._isDrawing = true; this._drawBrushPreview(pos.x, pos.y); } }
};

PixelPaintSkill._onCanvasMouseMove = function(e) {
    var self = this;
    if (this._isPanning) { var tab = this._getActiveTab(); if (!tab) return; tab.panX += e.clientX - this._panStartX; tab.panY += e.clientY - this._panStartY; this._panStartX = e.clientX; this._panStartY = e.clientY; this._updateViewport(); return; }
    if (!this._isDrawing) return; var pos = this._screenToGrid(e); if (!pos) return; var tab = this._getActiveTab();
    if (this._currentTool === 'brush') { if (!this._isValidBlock(this._selectedBlock)) return; var d = tab.data; if (this._lastDrawPos && this._lastDrawPos.x !== pos.x && this._lastDrawPos.y !== pos.y) { var x0=this._lastDrawPos.x,y0=this._lastDrawPos.y,x1=pos.x,y1=pos.y,dx=Math.abs(x1-x0),dy=Math.abs(y1-y0),sx=x0<x1?1:-1,sy=y0<y1?1:-1,err=dx-dy,cx=x0,cy=y0; while(true){if(cy>=0&&cy<d.length&&cx>=0&&cx<d[0].length){d[cy][cx]=self._selectedBlock;if(self._mergedData)self._mergedData[cy][cx]=self._selectedBlock;}if(cx===x1&&cy===y1)break;var e2=2*err;if(e2>-dy){err-=dy;cx+=sx;}if(e2<dx){err+=dx;cy+=sy;}} } else { d[pos.y][pos.x] = self._selectedBlock; if (self._mergedData) self._mergedData[pos.y][pos.x] = self._selectedBlock; } this._lastDrawPos = {x:pos.x,y:pos.y}; this._drawCell(pos.x, pos.y); }
    else if (this._currentTool === 'eraser') { var d2 = tab.data; if (this._lastDrawPos && this._lastDrawPos.x !== pos.x && this._lastDrawPos.y !== pos.y) { var x0e=this._lastDrawPos.x,y0e=this._lastDrawPos.y,x1e=pos.x,y1e=pos.y,dxe=Math.abs(x1e-x0e),dye=Math.abs(y1e-y0e),sxe=x0e<x1e?1:-1,sye=y0e<y1e?1:-1,erre=dxe-dye,cxe=x0e,cye=y0e; while(true){if(cye>=0&&cye<d2.length&&cxe>=0&&cxe<d2[0].length){d2[cye][cxe]=0;if(self._mergedData){var v=0;for(var li=0;li<self._layers.length;li++){if(!self._layers[li].visible||li===self._activeLayer)continue;var fd=(self._frameData[li]&&self._frameData[li][self._activeFrame])?self._frameData[li][self._activeFrame]:null;if(fd&&fd[cye][cxe]!==0){v=fd[cye][cxe];break;}}self._mergedData[cye][cxe]=v;}}if(cxe===x1e&&cye===y1e)break;var e2e=2*erre;if(e2e>-dye){erre-=dye;cxe+=sxe;}if(e2e<dxe){erre+=dxe;cye+=sye;}} } else { d2[pos.y][pos.x] = 0; if (self._mergedData) { var v2 = 0; for (var li2 = 0; li2 < self._layers.length; li2++) { if (!self._layers[li2].visible || li2 === self._activeLayer) continue; var fd2 = (self._frameData[li2] && self._frameData[li2][self._activeFrame]) ? self._frameData[li2][self._activeFrame] : null; if (fd2 && fd2[pos.y][pos.x] !== 0) { v2 = fd2[pos.y][pos.x]; break; } } self._mergedData[pos.y][pos.x] = v2; } } this._lastDrawPos = {x:pos.x,y:pos.y}; this._drawCell(pos.x, pos.y); }
    else if (this._currentTool === 'select') { if (this._selDragging && this._selData) { this._selX = pos.x - this._selDragOffX; this._selY = pos.y - this._selDragOffY; this._drawSelection(); } else if (this._drawStart) { this._selection.x2 = pos.x; this._selection.y2 = pos.y; this._drawSelection(); } }
    else if (this._currentTool === 'stamp' && this._selectedBrushIdx >= 0 && this._brushes[this._selectedBrushIdx]) { this._drawBrushPreview(pos.x, pos.y); }
};

PixelPaintSkill._onCanvasMouseUp = function(e) {
    var self = this;
    if (e.button === 2) { this._isPanning = false; this._canvasArea.style.cursor = 'crosshair'; return; }
    if (this._isDrawing) { if (this._currentTool === 'stamp' && this._selectedBrushIdx >= 0 && this._brushes[this._selectedBrushIdx] && this._brushPreviewPos) { var tab = this._getActiveTab(); if (tab) { this._pushUndo(tab); this._stampBrush(tab.data, this._brushes[this._selectedBrushIdx], this._brushPreviewPos.x, this._brushPreviewPos.y, tab.w, tab.h); this._drawCanvas(); this._autoSave(); } } this._clearBrushPreview(); if (this._currentTool === 'select') { if (this._drawStart && !this._selDragging) this._captureSelection(); else if (this._selDragging && this._selData) this._applySelection(); this._selDragging = false; } this._isDrawing = false; this._lastDrawPos = null; this._drawStart = null; this._saveCurrentFrame(); this._renderTimeline(); this._autoSave(); }
};

PixelPaintSkill._onCanvasWheel = function(e) { e.preventDefault(); var tab = this._getActiveTab(); if (!tab) return; var rect = this._canvasArea.getBoundingClientRect(); var mx = e.clientX - rect.left, my = e.clientY - rect.top; var oldZoom = tab.zoom; tab.zoom = Math.max(0.05, Math.min(8, tab.zoom * (e.deltaY > 0 ? 0.9 : 1.1))); var ratio = tab.zoom / oldZoom; tab.panX = mx - (mx - tab.panX) * ratio; tab.panY = my - (my - tab.panY) * ratio; this._updateViewport(); this._updateInfo(); };

PixelPaintSkill._onKeyDown = function(e) { if (e.target.tagName === 'INPUT') return; if (e.ctrlKey && e.key === 'z') { e.preventDefault(); this._undo(); return; } if (e.ctrlKey && e.key === 'y') { e.preventDefault(); this._redo(); return; } if (e.key === 'b') this._setTool('brush'); else if (e.key === 'e') this._setTool('eraser'); else if (e.key === 'g') this._setTool('fill'); else if (e.key === 's' && !e.ctrlKey) this._setTool('select'); else if (e.key === 'i') this._setTool('picker'); else if (e.key === 'Escape' && this._selLocked) this._cancelSelection(); };
